@HalbotWeb_HostAddress = http://localhost:5100

###
# @name postLogin
POST {{HalbotWeb_HostAddress}}/api/login
Accept: application/json
Content-Type: application/json

{
    "username":"admin",
    "password":"password"
}

###
@token = {{postLogin.response.body.token}}

###

GET {{HalbotWeb_HostAddress}}/api/activities/
Accept: application/json
Authorization: Bearer {{ token }}

###

POST {{HalbotWeb_HostAddress}}/api/logout
Accept: application/json
